### ISSUE TITLE
new-pr GitHub integration stuck on first try, works on second try

### ISSUE THREAD

**Issue by SethosII** [easybuilders/easybuild-framework#2415]
Whenever I use the `--new-pr` option for the first time in a session it gets stuck during `copying easyconfigs` like this:

```
$ eb --new-pr ChimPipe-0.9.5-foss-2016b-Python-2.7.12.eb --github-user SethosII --pr-commit-msg "Only SAMtools < 1.0 works"
== temporary log file in case of crash /tmp/eb-BpGrxu/easybuild-VZNOTH.log
== fetching branch 'develop' from https://github.com/easybuilders/easybuild-easyconfigs.git...
== copying easyconfigs to /tmp/eb-BpGrxu/git-working-dirBg8cNf/easybuild-easyconfigs...
# stuck here, no progress visible, also see attached log
^CTraceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/paul/easybuild/software/EasyBuild/3.5.0/lib/python2.7/site-packages/easybuild_framework-3.5.0-py2.7.egg/easybuild/main.py", line 504, in <module>
    main()
  File "/home/paul/easybuild/software/EasyBuild/3.5.0/lib/python2.7/site-packages/easybuild_framework-3.5.0-py2.7.egg/easybuild/main.py", line 421, in main
    commit_msg=options.pr_commit_msg)
  File "/home/paul/easybuild/software/EasyBuild/3.5.0/lib/python2.7/site-packages/easybuild_framework-3.5.0-py2.7.egg/easybuild/tools/github.py", line 1062, in new_pr
    commit_msg=commit_msg)
  File "/home/paul/easybuild/software/EasyBuild/3.5.0/lib/python2.7/site-packages/easybuild_framework-3.5.0-py2.7.egg/easybuild/tools/github.py", line 783, in _easyconfigs_pr_common
    res = my_remote.push(pr_branch)
  File "/usr/lib/python2.7/dist-packages/git/remote.py", line 696, in push
    return self._get_push_info(proc, progress or RemoteProgress())
  File "/usr/lib/python2.7/dist-packages/git/remote.py", line 601, in _get_push_info
    handle_process_output(proc, stdout_handler, progress_handler, finalize_process)
  File "/usr/lib/python2.7/dist-packages/git/cmd.py", line 166, in handle_process_output
    poll_result = poll.poll()
KeyboardInterrupt
```

Here is the [log](https://github.com/easybuilders/easybuild-framework/files/1767224/easybuild-VZNOTH.log).

However, it succeeds on the second try.

**Comment by boegel** [comment]
@SethosII It gets stuck when pushing the branch it has created to GitHub, apparently...

Can you try running `eb --check-github` in a new session, do you see something fishy being reported there? What if you run it a second time, is it different?

There was a DDOS attack on GitHub around the time you reported this issue, maybe it's related to the problems you were seeing? Or has this been occurring for a while?

(note that the just released EasyBuild v3.5.2 also has an issue with `--new-pr`, see #2423, I'm working on a fix and a quick v3.5.3 release to fix it)

**Comment by SethosII** [comment]
@boegel The odd thing is that the branch gets pushed. See here: https://github.com/SethosII/easybuild-easyconfigs/branches. There are two `ChimPipe` branches, one from the stuck command and another one from the second try.

`eb --check-github` also gets stuck on the first try:

```
$ eb --check-github
== temporary log file in case of crash /tmp/eb-K8iwCa/easybuild-4TdE24.log

Checking status of GitHub integration...

Making sure we're online...OK

* GitHub user...(none available) => FAIL
* GitHub token...(no token found) => FAIL
* git command...OK ("git version 2.7.4; ")
* GitPython module...OK (GitPython version 1.0.1)
# waited for 5 minutes and nothing happened
^C* push access to None/easybuild-easyconfigs repo @ GitHub...Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/paul/easybuild/software/EasyBuild/3.5.0/lib/python2.7/site-packages/easybuild_framework-3.5.0-py2.7.egg/easybuild/main.py", line 504, in <module>
    main()
  File "/home/paul/easybuild/software/EasyBuild/3.5.0/lib/python2.7/site-packages/easybuild_framework-3.5.0-py2.7.egg/easybuild/main.py", line 282, in main
    check_github()
  File "/home/paul/easybuild/software/EasyBuild/3.5.0/lib/python2.7/site-packages/easybuild_framework-3.5.0-py2.7.egg/easybuild/tools/github.py", line 1275, in check_github
    remote_name = setup_repo(git_repo, github_account, GITHUB_EASYCONFIGS_REPO, 'master', silent=True, git_only=True)
  File "/home/paul/easybuild/software/EasyBuild/3.5.0/lib/python2.7/site-packages/easybuild_framework-3.5.0-py2.7.egg/easybuild/tools/github.py", line 611, in setup_repo
    res = setup_repo_from(git_repo, github_url, target_account, branch_name, silent=silent)
  File "/home/paul/easybuild/software/EasyBuild/3.5.0/lib/python2.7/site-packages/easybuild_framework-3.5.0-py2.7.egg/easybuild/tools/github.py", line 558, in setup_repo_from
    res = origin.fetch()
  File "/usr/lib/python2.7/dist-packages/git/remote.py", line 655, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress or RemoteProgress())
  File "/usr/lib/python2.7/dist-packages/git/remote.py", line 553, in _get_fetch_info_from_stderr
    for line in proc.stderr.readlines():
KeyboardInterrupt
$ eb --check-github
== temporary log file in case of crash /tmp/eb-vqGNP5/easybuild-1ut8Lv.log

Checking status of GitHub integration...

Making sure we're online...OK

* GitHub user...(none available) => FAIL
* GitHub token...(no token found) => FAIL
* git command...OK ("git version 2.7.4; ")
* GitPython module...OK (GitPython version 1.0.1)
* push access to None/easybuild-easyconfigs repo @ GitHub...FAIL (no GitHub user specified)
* creating gists...OK
* location to Git working dirs... not found (suboptimal)

One or more checks FAILed, GitHub configuration not fully complete!
See http://easybuild.readthedocs.org/en/latest/Integration_with_GitHub.html#configuration for help.

Status of GitHub integration:
* --from-pr: OK
* --new-pr: not supported
* --review-pr: OK
* --update-pr: not supported
* --upload-test-report: not supported

```

Should I have provided the `--github-user` option? Here is the log file from the first try: [easybuild-4TdE24.log](https://github.com/easybuilders/easybuild-framework/files/1779710/easybuild-4TdE24.log).

The issue occured for me since I first used the github integration (after your hint here https://github.com/easybuilders/easybuild-easyconfigs/pull/5560#issuecomment-353746001). I didn't bother reporting it until now. So I don't think it is related to the DDoS attack.

**Comment by boegel** [comment]
@SethosII Interesting...

Please run `eb --check-github --debug` in a new session, and provide the log to us.

Also, check with providing `--github-user` as well to `eb --check-github` (but it probably won't make a difference for the hang).

Try to kill the running command from another session rather than cancelling with with Ctrl-C, that may make a difference for the log, we may get some more info.

The `GitPython` version you are using is quite old though, it's possible the problem is in there somewhere... This looks very similar (fixed in `GitPython` `1.0.2`, you're running `1.0.1`): https://github.com/gitpython-developers/GitPython/issues/295

**Comment by SethosII** [comment]
@boegel Here are output and logs with and without `--github-user` canceled with kill.

```
$ eb --check-github --debug
== temporary log file in case of crash /tmp/eb-bThdLy/easybuild-jRY7SH.log

Checking status of GitHub integration...

Making sure we're online...OK

* GitHub user...(none available) => FAIL
* GitHub token...(no token found) => FAIL
* git command...OK ("git version 2.7.4; ")
* GitPython module...OK (GitPython version 1.0.1)
Beendet
```

[easybuild-jRY7SH.log](https://github.com/easybuilders/easybuild-framework/files/1788005/easybuild-jRY7SH.log)

```
$ eb --check-github --github-user SethosII --debug
== temporary log file in case of crash /tmp/eb-hBSHjK/easybuild-ONep13.log

Checking status of GitHub integration...

Making sure we're online...OK

* GitHub user...SethosII => OK
* GitHub token...e01..9c3 (len: 40) => OK (validated)
* git command...OK ("git version 2.7.4; ")
* GitPython module...OK (GitPython version 1.0.1)
Beendet
```

[easybuild-ONep13.log](https://github.com/easybuilders/easybuild-framework/files/1788001/easybuild-ONep13.log)

The `GitPython` ist from the Ubuntu 16.04 repository: https://packages.ubuntu.com/search?keywords=python-git&searchon=names&suite=all&section=all. 18.04 will come with a much more recent version. I tested the code snippet from the referenced issue but it doesn't hang on the fetch as described there. But it also doesn't ask me for credentials.

**Comment by boegel** [comment]
@SethosII OK, this helps...

It seems like it's the `git clone` that gets stuck. Can you try a manual `git clone git@github.com:SethosII/easybuild-easyconfigs.git` in a new session, does that also get stuck?

It seems like several related issues have been solved in more recent versions of `GitPython`, so I would definitely look into trying a new version of `GitPython`, I don't think there's much we can do on the EasyBuild side for this...

**Comment by SethosII** [comment]
@boegel Cloning manually runs without problems.

I grabbed the 18.04 package of `python-git` and updated dependencies (`python-gitdb` and `python-smmap`) but it still gets stuck while cloning:

```
$ eb --check-github --github-user SethosII --debug
== temporary log file in case of crash /tmp/eb-8EYTFt/easybuild-0WUvIV.log

Checking status of GitHub integration...

Making sure we're online...OK

* GitHub user...SethosII => OK
* GitHub token...e01..9c3 (len: 40) => OK (validated)
* git command...OK ("git version 2.7.4; ")
* GitPython module...OK (GitPython version 2.1.8)
Beendet
```

[easybuild-0WUvIV.log](https://github.com/easybuilders/easybuild-framework/files/1788772/easybuild-0WUvIV.log)

**Comment by SethosII** [comment]
@boegel I encountered something similar while using `--update-pr`. See this commit: https://github.com/easybuilders/easybuild-easyconfigs/pull/5930/commits/eadee0a8f4fb62c7b12e9d4f1bbe35bde654b791. `--update-pr` gets stuck but succeeded to push and got the author and commiter wrong:

```
$ eb --update-pr 5930 ChimPipe-0.9.5-foss-2016b-Python-2.7.12.eb --github-user SethosII --pr-commit-msg "Add comment for SAMtools version requirement"
== temporary log file in case of crash /tmp/eb-CJEkDU/easybuild-S_qio1.log
== Determined branch name corresponding to easybuilders/easybuild-easyconfigs PR #5930: 20180228132600_new_pr_ChimPipe095
== fetching branch '20180228132600_new_pr_ChimPipe095' from https://github.com/SethosII/easybuild-easyconfigs.git...
== copying easyconfigs to /tmp/eb-CJEkDU/git-working-dirna0lmo/easybuild-easyconfigs...
# stuck here, commit got pushed but author and commiter is my local username
^C
# doesn't react to CTRL+C
```

[easybuild-S_qio1.log](https://github.com/easybuilders/easybuild-framework/files/1818351/easybuild-S_qio1.log)

**Comment by boegel** [comment]
@SethosII Sorry for not getting back to this, but the cause of the issue is still unclear to me... You're using what's pretty much the latest version of `GitPython`, so we can't blame it on an old version either.

What's strange is that I haven't heard from anyone else with problems like this, so it must be something in your setup.

The faulty author in the commit intrigues me... I assume it didn't get `paul` out of thin air?

Do you have a particular `git` configuration in place that may screw things up?

I wonder if someone from @gitpython-developers has any ideas here, because I'm running out...

**Comment by SethosII** [comment]
@boegel No problem. And if nobody else encountered it I can live with the issue. `paul` is my local account name there. So it ignored the `--github-user` (Github username) and `.gitconfig` (full name) in this situation. I don't have special `git` configurations in place. The `.gitconfig` only contains name and email and there is no special configuration for the repository.
